export const DEMO_USER = {
  id: 'demo-user-1',
  email: 'pedro@mail.wlu.edu',
}

export const DEMO_CONTACTS = [
  {
    id: '1',
    name: 'Blair Garrou',
    grad_year: 1996,
    company: 'Mercury Fund',
    role: 'Co-founder & Managing Partner',
    industry: 'Finance',
    how_they_help: 'Runs a Texas-based early-stage VC firm managing $1B+ in assets. Chairs the W&L Entrepreneurship Advisory Board. Open to mentoring student founders and reviewing pitch decks.',
    tags: ['venture capital', 'early-stage', 'advisory board'],
    added_by: 'demo-user-2',
    created_at: '2026-03-20T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '2',
    name: 'Chip Mahan',
    grad_year: 1973,
    company: 'Live Oak Bancshares / Canapi Ventures',
    role: 'Founder, CEO & Chairman',
    industry: 'Finance',
    how_they_help: 'Founded Live Oak Bank, co-founded Canapi Ventures (fintech VC) and nCino (cloud banking, now public). Can speak to building companies from zero and fintech landscape.',
    tags: ['fintech', 'banking', 'founder', 'public company'],
    added_by: 'demo-user-1',
    created_at: '2026-03-19T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '3',
    name: 'Reuben Munger',
    grad_year: 1995,
    company: 'Vision Ridge Partners',
    role: 'Founder & Managing Partner',
    industry: 'Finance',
    how_they_help: 'Founded Vision Ridge, a sustainable real assets investment firm. Previously a Partner at The Baupost Group. Interested in connecting with students passionate about climate investing.',
    tags: ['sustainable investing', 'climate', 'real assets'],
    added_by: 'demo-user-3',
    created_at: '2026-03-18T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '4',
    name: 'Ethan Smith',
    grad_year: 2010,
    company: 'Spur',
    role: 'Co-founder & CEO',
    industry: 'Tech',
    how_they_help: 'Built Spur (cybersecurity) to nearly $15M ARR with zero outside investment. Protects 50%+ of Fortune 50. Former DoD. Great resource on bootstrapping and cybersecurity.',
    tags: ['cybersecurity', 'bootstrapped', 'founder'],
    added_by: 'demo-user-2',
    created_at: '2026-03-17T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '5',
    name: 'Athena Meyers',
    grad_year: 2000,
    company: 'Niche',
    role: 'Chief Product Officer',
    industry: 'Tech',
    how_they_help: 'CPO at Niche, a growth-stage startup modernizing school discovery. Launched Direct Admissions — TIME\'s Best Inventions 2024. Can speak to joining early-stage startups and building product from zero to scale.',
    tags: ['startup leadership', 'edtech', 'product', 'growth stage'],
    added_by: 'demo-user-1',
    created_at: '2026-03-16T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '6',
    name: 'Greg Barrow',
    grad_year: 1987,
    company: 'General Capital Partners',
    role: 'Founder & Managing Director',
    industry: 'Finance',
    how_they_help: 'Founded GCP in 2002, completed 150+ transactions across manufacturing, real estate, energy, and consumer products. Active CES EIR. Office hours available during campus visits.',
    tags: ['private equity', 'acquisitions', 'EIR'],
    added_by: 'demo-user-3',
    created_at: '2026-03-15T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '7',
    name: 'Stephanie Lind',
    grad_year: 1992,
    company: 'Elohi Strategic Advisors',
    role: 'Founder & CEO',
    industry: 'Consulting',
    how_they_help: 'Global consulting for food/bev startups. Previously Head of Global Sales at Impossible Foods. W&L\'s inaugural Entrepreneur-in-Residence. Deeply invested in mentoring students.',
    tags: ['food & bev', 'CPG', 'go-to-market', 'EIR'],
    added_by: 'demo-user-2',
    created_at: '2026-03-14T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '8',
    name: 'Abhinav Kapur',
    grad_year: 2008,
    company: 'Bikky',
    role: 'Co-founder & CEO',
    industry: 'Tech',
    how_they_help: 'Built Bikky, a customer data platform for multi-unit restaurants. Previously in IB and equity research. Can advise on pivoting from finance to founding.',
    tags: ['SaaS', 'restaurants', 'founder', 'data'],
    added_by: 'demo-user-1',
    created_at: '2026-03-13T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '9',
    name: 'Ted Elliott',
    grad_year: 1994,
    company: 'Copado',
    role: 'CEO',
    industry: 'Tech',
    how_they_help: 'Scaled Copado from 30 to 700+ employees and $4.5M to $60M+ ARR, reaching $1.9B unicorn status. Previously CEO of Jobscience (sold to Bullhorn). Five W&L alumni on Copado\'s management team. Connolly Center advisory board member.',
    tags: ['unicorn', 'SaaS', 'DevOps', 'Salesforce', 'CEO'],
    added_by: 'demo-user-3',
    created_at: '2026-03-12T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '10',
    name: 'Eric Herrera',
    grad_year: 2020,
    company: 'MaverickX',
    role: 'Co-founder & CEO',
    industry: 'Tech',
    how_they_help: 'Forbes 30 Under 30. Y Combinator backed. Uses mRNA science for non-toxic chemical extraction. Can advise on deep tech fundraising, YC applications, and going from college to startup.',
    tags: ['deep tech', 'Y Combinator', 'Forbes 30u30', 'climate'],
    added_by: 'demo-user-2',
    created_at: '2026-03-11T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '11',
    name: 'Matt Bartini',
    grad_year: 2012,
    company: 'Mayor Clothing',
    role: 'Founder & CEO',
    industry: 'Startup',
    how_they_help: 'Built a custom-print apparel brand for golf clubs, resorts, and colleges. Fall 2025 EIR. Great resource on DTC brands, manufacturing, and sales.',
    tags: ['DTC', 'apparel', 'EIR', 'manufacturing'],
    added_by: 'demo-user-1',
    created_at: '2026-03-10T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '12',
    name: 'Byron Burns',
    grad_year: 1998,
    company: 'Red Iron Partners / Carolina Recording Systems',
    role: 'Co-founder / President',
    industry: 'Tech',
    how_they_help: 'Co-founded Red Iron Partners (private investment) and runs Carolina Recording Systems (mission-critical 911 recording). Can advise on acquisitions and niche B2B software.',
    tags: ['private investment', 'B2B', 'acquisitions', 'EIR'],
    added_by: 'demo-user-3',
    created_at: '2026-03-09T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '13',
    name: 'Luke Doiron',
    grad_year: 2000,
    company: 'Discovery Life Sciences',
    role: 'Co-founder & EVP',
    industry: 'Healthcare',
    how_they_help: 'Co-founded Discovery Life Sciences, a biospecimen and genomic services company. Can speak to biotech entrepreneurship and life sciences fundraising.',
    tags: ['biotech', 'life sciences', 'co-founder'],
    added_by: 'demo-user-2',
    created_at: '2026-03-08T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '14',
    name: 'Larry Connolly',
    grad_year: 1979,
    company: 'Connolly Inc.',
    role: 'Former CEO & Co-owner',
    industry: 'Startup',
    how_they_help: 'Grew Connolly Inc. (recovery audit consulting) from 30 to 1,250+ employees, sold to Advent International in 2012. W&L\'s entrepreneurship center is named after him. Can speak to scaling services businesses and exits.',
    tags: ['scaling', 'exit', 'PE acquisition', 'namesake'],
    added_by: 'demo-user-1',
    created_at: '2026-03-07T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: '15',
    name: 'Cory Allison',
    grad_year: 1994,
    company: 'KelCor',
    role: 'Founder & CEO',
    industry: 'Startup',
    how_they_help: 'Founded KelCor, a manufacturing and product company. Regular E-Summit speaker on "Making Real Stuff" — great for hardware and physical product founders.',
    tags: ['manufacturing', 'hardware', 'physical products'],
    added_by: 'demo-user-3',
    created_at: '2026-03-06T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
]

export const DEMO_REQUESTS = [
  {
    id: 'req-1',
    requester_id: 'demo-user-3',
    contact_id: '2',
    message: "I'm building a fintech project for my capstone and would love to learn about Chip's journey founding Live Oak Bank and Canapi Ventures. A 15-minute call would be incredible.",
    status: 'pending',
    created_at: '2026-03-21T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: 'req-2',
    requester_id: 'demo-user-2',
    contact_id: '5',
    message: "I'm interested in product management and would love to hear about Athena's path to CPO at Niche, especially the Direct Admissions launch.",
    status: 'pending',
    created_at: '2026-03-20T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
  {
    id: 'req-3',
    requester_id: 'demo-user-3',
    contact_id: '10',
    message: "We're applying to YC next batch — would love Eric's advice on the application process and what helped MaverickX stand out.",
    status: 'accepted',
    created_at: '2026-03-18T10:00:00Z',
    profiles: { display_name: 'Pedro Liron de Robles', email: 'plironderobles@mail.wlu.edu' },
  },
]
